# Generated by Django 3.1.2 on 2022-02-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
