# Generated by Django 3.1.2 on 2022-02-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_persons_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
